version: "3.8"

services:

  ca-gateway:
    image: pklaus/ca-gateway
    container_name: ca-gateway
    expose:
      - "5064-5065/udp"
      - "5064-5065"
    ports:
      - "5064-5065:5064-5065/udp"
      - "5064-5065:5064-5065"
    restart: always
    networks:
      # the network that's alphabetically first will be the one with the forwarded ports
      a_epics_supervisory:
        ipv4_address: 10.2.2.2
      epics_field:
        ipv4_address: 172.20.255.254
    volumes:
      - ../_conf/access:/access:ro
      - ../_conf/pvlist:/pvlist:ro
    command: -sip 10.2.2.2 -cip 172.20.255.255 -pvlist /pvlist -access /access -log /dev/stdout -debug 1

  softioc:
    image: pklaus/epics_base:7.0.4_debian
    stdin_open: true
    tty: true
    working_dir: /epics/iocs/example/iocBoot/iocEXAMPLE
    expose:
      - "5064-5065/udp"
      - "5064-5065"
    networks:
      - epics_field
    command: ./st.cmd

  camonitor_on_supervisory:
    image: pklaus/epics_base:7.0.2.2_debian
    networks:
      - a_epics_supervisory
    stdin_open: true
    tty: true
    command: /bin/bash -c "sleep 5 && camonitor scs:ai1"

networks:

  # alphabetically first, so that port forwardings get to this network
  # but do we need forwarding in this mode???
  a_epics_supervisory:
    driver: macvlan
    driver_opts:
      # vlan 87
      #parent: eth1.87
      parent: enp10s0
    ipam:
      config:
        - subnet: 10.2.0.0/16
          #docker-compose v2 file only:
          #gateway: 10.2.0.1
          #ip_range: 10.2.2.0/24 # IP from this pool are assigned automatically

  epics_field:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
